bin/sphenix_setup.csh
bin/sphenix_setup.sh

so we can switch to /opt in afs even if the /opt softlink points to cvmfs. Just in case we need to roll back quickly

replace /opt/sphenix by full afs path

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

the previous path in /afs messed with the container. This will be put back in once we switch to cvmfs for the afs version

replace afs path to /opt/sphenix again by direct /opt/sphenix

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This should finally fix the crashing play builds which use a newer G4 version

unset XERCESCROOT to be able to switch to the play build

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

now that we have switched /opt/sphenix to point to cvmfs it needs a small change to switch to the afs environment - replacing /opt/sphenix by /afs/rhic.bnl.gov/opt/sphenix in the setting of OPT_SPHENIX and OPT_UTILS

get afs sphenix environment

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

the setup script needs a small change so the containers which use /opt/sphenix can run it. This is basically the cvmfs version of our setup scripts (also enabling pyroot)

use with /opt/sphenix -> /cvmfs

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh
etc/config_debug.site

Just changing the CXXFLAGS in the config.site is the easiest way to get consistent builds using -std=c++11 which is set to our default in this file, rather than overriding CXXFLAGS for every single package. This needed to be propagated to the setup scripts which now set CONFIG_SITE to ${OPT_SPHENIX}/etc/config_debug.site if sourced with debug

Debug build

---

bin/setup_root6.csh
bin/setup_root6.sh
bin/sphenix_setup.csh
bin/sphenix_setup.sh

the previous version was a quick hack to avoid random user arguments which get passed to the sphenix_setup script to confuse the setup_root6 script. Calling this script now with $OFFLINE_MAIN takes care of that. This also prevents adding offline_main includes twice in case a user calls the setup_root6 script with OFFLINE_MAIN as argument.

Fix argument handling

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

We have to fall back to python 3.6, these &*#^$*^ exported a private symbol which prevents root6 from linking. We are not alone:
https://bugzilla.redhat.com/show_bug.cgi?id=1596902
It also has an API change from char * to const char * which makes minor code changes in root5 and root6 necessary (which doesn't feel good either)

change python version back to 3.6

---

bin/setup_root6.csh
bin/setup_root6.sh

Up to now the script loops over all subdirs under $OFFLINE_MAIN/include and adds them to the ROOT_INCLUDE_PATH. This is not needed anymore - we are still left with 4 oddball subdirs which are needed but adding all is an overkill and might hide problems in the code. Now those oddball subdirs are hardcoded into the include path. It still loops over the user install area (if given) and adds all subdirs.

only add absolutely needed paths from OFFLINE_MAIN, not all subdirs

---

bin/get_build_tags.pl

This PR adds a small perl script which prints out the git tags of a given build in case someone wants to recover the sources

list tags for a given build from DB

---

bin/setup_local.csh
bin/setup_local.sh

This PR adds a script (bash and tcsh) which sets up the PATH, LD_LIBRARY_PATH and ROOT_INCLUDE_PATH correctly for private install areas. Multiple install areas can be given, they are added in the order they are given (the first one being first in the path)

scripts which set up private install areas correctly

---

bin/setup_root6.csh
bin/setup_root6.sh

It is still a mystery how root6 deals with the include path. The EIC macro stopped to work with the latest PR without having g4main in the include path (barfs with #include "PHG4HitDefs.h").

Add g4main to ROOT_INCLUDE_PATH

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR switches our insure version to the newest version (no it doesn't work just like the other ones, we do not have a root insure exec)

make insure 7.5.2 the default

---

bin/sphenix_setup.sh

This PR fixes the missing SARTRE_DIR env var from the sphenix setup script

oops, forgot a $ in the env var check

---

bin/setup_local.csh
bin/setup_local.sh
bin/sphenix_setup.csh
bin/sphenix_setup.sh

our initial cvmfs volume /cvmfs/sphenix.sdcc.bnl.gov was hardcoded in a few places which threw the use of our OSG volume /cvmfs/sphenix.opensciencegrid.org off. Now the location of the sphenix_setup scripts is used to determine the installation location. The setup scripts have an option to override this but I would use this only for testing a modified script

use location of setup script to determine installation location

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR just sets up the gcc8.3 compiler if it is found under $OPT_SPHENIX

add setting of gcc 8.3 so we can use unified sphenix setup scripts

---

bin/sphenix_setup.csh

This PR handles the case for cron jobs where $0 comes as /bin/tcsh but the path and name of the script itself is not available (at least I have not figured out a way to get it). For the time being the crontabs have to use -b[basedir] to work

cron jobs yet behave differently again

---

bin/sphenix_setup.csh
bin/sphenix_setup_new.csh

Put the old sphenix_setup.csh back in place. It ignores the -b option of someone set it in the meantime. That restores the old behavior. The sphenix_setup_new.csh is the replacement which can be used for testing the automatic setting of the base installation directory

Revert setup

---

bin/sphenix_setup.csh

This branch is for the gcc 8.3 cvmfs volume on the opensciencegrid

replace sdcc with opensciencegrid to use the opensciencegrid

---

bin/sphenix_setup.sh

This PR fixes a good catch by Bing, even if -b was not used, force_base would be "ne", if by chance a directory of that name exists this would really mess things up

fix issue where force_base would be ne

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

That PR should unify the setup scripts between gcc 4.8 on x8664 and gcc 8.3. The adjustments for the cvmfs volumes (sdcc or opensciencegrid) are done by separate shell scripts

Unify x8664 gcc83

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

The gcc 8.3 setup script sets a few environment variables which need to be unset, otherwise you will use that compiler even when switching environments

unset environment variables which are set by gcc 8.3

---

bin/sphenix_setup.sh

This PR fixes the MANPATH setting when switching cvmfs volumes. Previously the old PATH crept into the manpath since man --path used the old path (it is overridden later). Now the MAANPATH setting starts using the new default path and takes it from there

correct MANPATH when switching cvmfs volumes

---

bin/eic_setup.csh
bin/eic_setup.sh

This PR just adds softlinks so eic users do not have to source an sphenix setup script

add softlinks for eic setup, pointing to sphenix setup

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

Andrea had problems with afs not being installed. This PR checks for /usr/bin/fs before calling it, sets sysname to x8664_sl7 if this is not found

in case afs is missing, set sysname to x8664_sl7

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR puts the PGUSER env var back. It is needed so we can access our DBs without adding a user name to the connection string. The PGHOST is now set to sphnxdbmaster

Add pguser

---

bin/setup_local.csh
bin/setup_local.sh

When allowing libraries to be installed in /lib64 I forgot to add this to the setup_local scripts, so local installations only added /lib to the LD_LIBRARY_PATH. Now it also adds /lib64 if it exists

Add lib64 of local install to LD_LIBRARY_PATH

---

etc/config.site
etc/config_debug.site

When allowing packages to install libraries into /lib64 I forgot to update the setup_local scripts accordingly which up to now only added /lib to the LD_LIBRARY_PATH. Now also install/lib64 is added if it exists

Add local lib64 gcc 8.3

---

bin/setup_root6_include_path.csh
bin/setup_root6_include_path.sh

This PR appends the install location of the common root macros ($OFFLINE_MAIN/rootmacros) to the ROOT_INCLUDE_PATH. Our new Fun4All_G4_XXX.C and G4Setup_XXX.C macros which describe a specific detector pick them up from there. If one has a local copy it overrides that (that needs to be checked). This change does not interfere with the old macros

append rootmacros to ROOT_INCLUDE_PATH

---

bin/step-gdml.sh

This PR uses $OPT_SPHENIX instead of hardcoded /cvmfs/... so this script does not have to be adjusted when copying to other cvmfs volumes (or systems)

replace hardcoded sysname in path

---

bin/setup_root6_include_path.csh
bin/setup_root6_include_path.sh

This PR adds ./ to the beginning of the ROOT_INCLUDE_PATH to pick up local includes first This is needed that local macros are consistently favored over the centrally installed ones (needs a macro change include "" --> include <> which will come next)

Root6 incpath

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR reverses a previous one. It turns out that cmake looks at CXX , CC and so on. Removing these env vars leaves cmake choosing the SL7 stock compiler gcc 4.8

unsetting CXX etc kills cmake

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR sets PARASOFT to /afs/rhic.bnl.gov/app/insure-7.5.5

upgrade to insure 7.5.5

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR fixes a serious problem in the setup scripts. They are under no circumstances to print out anything. The addition of the one time S3 setup resulted in blurbs coming out of setting it up. After fixing this (pipe to /dev/null as recommended) doing a grep in a non existing directory spat some more characters on the screen. The new version checks for the directory before it does grep.

remove printout which will kill winsshfs at BNL

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR fixes the GSEARCHPATH. Only sphenix accounts with the sphenix gid can access lustre via xrootd, phenix accounts with sphenix as secondary gid use minio

remove DCACHE from GSEARCHPATH, keep XROOTD for sh, MINIO for tcsh

---

etc/sPHENIX_cdb_write.json

This PR adds the json config to write to the sPHENIX conditions DB and read back immediately

Add json file for writing to sPHENIX CDB

---

bin/setup_root6_include_path.csh
bin/setup_root6_include_path.sh

This PR removed $OFFLINE_MAIN/include/gloo from the ROOT_INCLUDE_PATH. It is installed by copying pytorch and it contains linux system include overrides which if root picks them up will cause problems

old leftover - remove gloo from ROOT_INCLUDE_PATH, it contains system includes from pytorch

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

clang needs gcc 8.3, llvm does not build with gcc 12 so far

clang needs gcc 8.3 so far

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR adds the pdf path for LHAPDF 6 and adds it to the PYTHONPATH. This should finally enable us to run the lhapdf python script to fetch pdfs

set up LHAPDF

---

etc/sPHENIX_newcdb.json

This PR moves the cdb to it's final location (/cvmfs/sphenix.sdcc.bnl.gov/calibrations/sphnxpro/cdb)

move cdb files from cdbtest to cdb

---

etc/sPHENIX_newcdb.json

This PR tries this again - update only sPHENIX_newcdb.json with the new server, leave old files intact for legacy use

use new server

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

if CPLUS_INCLUDE_PATH is set it creates a subtle change in the include path order which wreak havoc in our build but is very hard to find. We do not use this but other packages might do. This pre-emptively unsets it when sourced with -n

unset CPLUS_INCLUDE_PATH with -n, bad behavior if set, remove obsolete coverity

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR changes the default build from new to ana to avoid old sessions locking outdated files in cvmfs

set default build to ana

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR sources the rucio setup script from our /cvmfs/sphenix.sdcc.bnl.gov/rucio-clients area if it exists

source rucio setup script from sphenix setup script

---

etc/sPHENIX_newcdb.json
etc/sPHENIX_newcdb_debug.json

5 cdb retries are likely not enough under heavy load, increase to 50

increase cdb tries to 50 which should deal with 50k simultaneous jobs

---

bin/sphenix_setup.csh
bin/sphenix_setup.sh

This PR sets the PERL5LIB env var to the correct location for almalinux9 gcc 14.2.0

correct PERL5LIB env var

---

etc/sPHENIX_newcdb.json
etc/sPHENIX_newcdb_debug.json

A stuck pod was the reason for the slowness using the new url last time. That's been fixed - this switches us again to the new url for the cdb

use new cdb url
