sPHENIX-Collaboration/opt_sphenix_scripts

bin/sphenix_setup.csh, bin/sphenix_setup.sh
the ordering of directories in the path and LD_LIBRARY_PATH was very different between the bash and csh script. Rather than sorting through this spaghetti code, now the setup of the paths is done in a loop using previously set up environment vars. That makes it much easier to keep them in sync and reduces the amount of lines drastically
=> total revamp - now all env vars are set in a loop

bin/sphenix_setup.csh
small patch to deal with the pwd alias in the STAR environment
=> unalias pwd which is set in STARs environment

bin/sphenix_setup.csh, bin/sphenix_setup.sh
small fix, this bug was hiding behind geant4-config adding the correct include and lib path
=> xercesroot needs to point to OPT_SPHENIX/geant4

bin/sphenix_setup.csh, bin/sphenix_setup.sh
That fix should finally get the play build with the updated G4 version working
=> unset XERCESCROOT to be able to switch to the play build

bin/setup_root6.csh, bin/setup_root6.sh, bin/sphenix_setup.csh, bin/sphenix_setup.sh
add setup_root6sh for bash users, source setup_root6 scripts from sphenix_setup scripts
=> Fix setuproot6

bin/sphenix_setup.csh, bin/sphenix_setup.sh
we have a new python version. I guess at some point we can read this from the python exec but for the time being this is hardcoded
=> change python version to 3.7

bin/sphenix_setup.sh
PYTHIA8 was not set, some other vars had similar issues
=> fix typos, -z needs double quotes, not sure how the rest worked

bin/setup_root6.csh, bin/setup_root6.sh
GenFit needs this one to load its lib
=> Add GenFit include dir to ROOT_INCLUDE_PATH

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR gets us to the newest version of coverity
=> upgrade coverity to coverity-2019.03

bin/setup_root6.csh, bin/setup_root6.sh
with this kludge we can read back DSTs containing track objects
=> add trackbase_historic to kludged ROOT_INCLUDE_PATH

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR sets the default insure version to 7.5.3 (from 7.5.2)
=> set parasoft version to 7.5.3

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR makes it possible to run the Sartre event generator
=> Add setting of SARTRE_DIR to run Sartre

bin/setup_root6_include_path.csh, bin/setup_root6_include_path.sh
this PR removes the rave include dir from the ROOT_INCLUDE_PATH
=> remove rave from ROOT_INCLUDE_PATH

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR sets the python path to the sitewide 3.8 packages
=> upgrade to python3.8, move from utils to core

bin/setup_local.csh, bin/setup_local.sh, bin/sphenix_setup.csh
propagate change from master branch, use OPT_SPHENIX intead of hardcode /opt/sphenix/core. sphenix_setup.csh script ignores -b option
=> use OPT_SPHENIX for opt area, rather than hardcoded /opt/sphenix

bin/sphenix_setup.csh
This branch should be used on the opensciencegrid cvmfs volume
=> replace sdcc with opensciencegrid 

bin/setup_root6_include_path.sh
This PR should stop the generation of those 0 files
=> Martin found how the 0 file got created, use -gt instead of >

bin/setup_local.sh
another $#>0 instead of -gt 0 in a bash script
=> oops - another 0 > 0 instead of -gt 0

bin/setup_local.sh, bin/setup_root6_include_path.sh
This PR cleans up locally used variables which otherwise stick around confusing everyone
=> Unset bash local vars

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR is for users with local eic cvmfs copies where /opt/sphenix is replaced by /opt/fun4all
=> works if /opt/sphenix is replaced by /opt/fun4all

bin/sphenix_setup.csh, bin/sphenix_setup.sh
propagate changes from x8664_sl7 to gcc-8.3
=> Opt fun4all gcc 8.3

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR adds the gsearchpath used by the file catalog
=> add GSEARCHPATH for file catalog searches

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR adds the GSEARCHPATH which is used by the file catalog
=> Gsearchpath

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR just updates the comment at the beginning (remove PHENIX remnant)
=> fix comments, they were still from PHENIX

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR adds XROOTD to the GSEARCHPATH - hail mary to fix alleviate dcache access
=> Add XROOTD to GSEARCHPATH

bin/sphenix_setup.csh, bin/sphenix_setup.sh
We have a new coverity version - yeah
=> switch to coverity-2021.12

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR sets now the XPLOAD_CONFIG_DIR
=> set XPLOAD_CONFIG_DIR

etc/sPHENIX_cdb.json
This PR adds the current read path to cvmfs including the fallback to gpfs
=> add read path includign fallback to gpfs filesystem

etc/wild_west_cdb.json
Add the config of our Wild West CDB
=> Add config for new user test db

bin/ecce_setup.csh, bin/ecce_setup.sh, bin/eic_setup.csh, bin/eic_setup.sh, bin/sphenix_setup.csh, bin/sphenix_setup.sh, etc/config.site, etc/sPHENIX_cdb.json, etc/sPHENIX_cdb_write.json, etc/wild_west_cdb.json
Changes for the new area for use by gcc 12.1.0
=> Gcc 12.1.0

bin/sphenix_setup.csh, bin/sphenix_setup.sh
LHAPDF data env var added, python packages in $OFFLINE_MAIN now in the python path
=> add LHAPDF 6

etc/config.site
This PR adds new suppressions for clang14
=> new flags for clang 14

bin/sphenix_setup.csh, bin/sphenix_setup.sh
This PR sets our no payload db config in our setup scripts
=> Add our nopayload client config

etc/sPHENIX_newcdb.json
This PR updates the cdb json file with more required values for cdb client update
=> add new variables to sPHENIX_newcdb.json

bin/sphenix_setup.csh, bin/sphenix_setup.sh
accidentally left the old definition in place
=> set pghost correctly

bin/sphenix_setup.csh, bin/sphenix_setup.sh, etc/sPHENIX_cdb_write.json, etc/sPHENIX_newcdb.json, etc/wild_west_cdb.json
Reverts sPHENIX-Collaboration/opt_sphenix_scripts#143
For the sim production which uses old ana builds we need the old files
=> Revert "New cdb"

etc/sPHENIX_cdb.json, etc/sPHENIX_cdb_write.json
Trying to revive sim production with old xpload ana builds
=> move old cdb implementation to new legacy server

etc/sPHENIX_newcdb.json
THe new client has a  two new fields
=> new entries for next cdb client

bin/sphenix_setup.csh, bin/sphenix_setup.sh
Cleanup - comment out unused setups
=> comment out rucio and s3 setup

etc/sPHENIX_newcdb_debug.json
This PR adds another cdb config file which enables debug logging
=> Add cdb wioth debug log

etc/sPHENIX_newcdb.json
set sleep to 100 for regular and debug config
=> add sleep between retries parameter

bin/sphenix_setup.csh, bin/sphenix_setup.sh
The csh script is work in progress - the bash script is behind
=> start with setup scripts for alma9

bin/sphenix_setup.csh, bin/sphenix_setup.sh
decided to go with gcc 14.2 released this summer
=> adjust for gcc 14.2.0, need our own perl version bc rh annobin

bin/sphenix_setup.sh
the bash script sourced the wrong compiler setup script
=> fix bad path for compiler setup

bin/step-gdml.sh
step gdml does not build anymore and is not maintained, needs replacement if we ever need this
=> remove obsolete step-gdml.sh

bin/sphenix_setup.sh
accidental copied set command from tcsh script
=> remove tcsh mixup

bin/get_build_tags.pl, bin/getinputfiles.pl
That should get the perl scripts to work under alma9
=> use /usr/bin/env perl in perl scripts to use with alma9

etc/sPHENIX_newcdb.json, etc/sPHENIX_newcdb_debug.json
That change froze the cdb - falling back to the previous url
=> fall back to old url

bin/setup_root6_include_path.csh, bin/setup_root6_include_path.sh
so we can use odbc calls in macros
=> add /opt/sphenix/core/include to root include path
